### ISSUE TITLE
Can you make this for CentOS?

### ISSUE THREAD

**Issue by ramonberrutti** [burnedram/eBoot-CSGO#1]
Like title say, whey will be a nice option :)

**Comment by burnedram** [comment]
Hi ramonberruti, I have no knowledge of CentOS, so I'm not sure what would differ/be needed in order to "port" this to CentOS.
However, you should be able to follow the Makefile line by line in order to get some insight in what would be needed for you to replicate what the script does.
I'm sorry I can't really help you, but this was created mostly keep track of all the problems in eBot. With that said, all the *.patch files should work just the same for you, so feel free to use them!
